version: '3'
services:
    frontend:
        build: ./frontend
        ports:
          - "80:80"
        networks:
          - my_app_network
    backend:
        build: .
        ports:
          - "5000:5000"
        depends_on:
          - database 
        networks:
          - my_app_network  
    database:
        image: mongo
        ports:
          - "27017:27017"
        networks:
          - my_app_network  
networks:
    my_app_network:
        driver: bridge          
